kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-sctp-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "service-sctp",
            "label": "CNF_TCP",
            "remark": "A1-2 Template",
            "vzn": {
                "class": "Tenant"
            }
        }
    }
