kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-sctp-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.17.0",
            "id": "service-sctp",
            "label": "CNF_TCP",
            "remark": "A1-2 Template",
            "vzn": {
                "class": "Tenant",
                "f5_hello_world": {
                    "class": "Application",
                    "template": "generic",
                    "CNF_VS_132": {
                        "class": "Service_SCTP",
                        "remark": "a1",
                        "virtualAddresses": [
                            "10.75.70.5"
                        ],
                        "virtualPort": 132,
                        "pool": "cnf_pool_132"
                    },
                    "cnf_pool_132": {
                        "class": "Pool",
                        "monitors": [
                            "icmp"
                        ],
                        "members": [
                            {
                                "servicePort": 132,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
